id: 0a9ab50e1034424a8c5b689163882b56
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_174-The_Inquiry_of_Lokadhara-v2
  language: bo
  author: ''
  volume: {}
